### Obtener todas las reservas
GET http://localhost:3000/api/reservas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbCI6ImFkbWluIiwiaWF0IjoxNzAyODc5ODE3LCJleHAiOjE3MDI4ODM0MTd9.Mo2NkDE4zRazPe0ITDkGEn5C0YVRZEs5v5dHTV2KSqs

### Obtener una reserva
GET http://localhost:3000/api/reservas/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA

###Obtener reserva de cliente
GET http://localhost:3000/api/reservas/id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA

### Crear una nueva reserva
POST http://localhost:3000/api/reservas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA
Content-Type: application/json

{
  "fechaHora": "2023-10-29T22:00:00Z",
  "cantidadPersonas": 6,
  "estado": "Pendiente",
  "cliente": 2,
  "Mesas": [
    {
      "id": 2
    },
    {
      "id": 3
    }
  ]
}

### Modificar una reserva (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/reservas/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA
Content-Type: application/json

{
  "estado": "Completada"
}

### Borrar una reserva
DELETE http://localhost:3000/api/reservas/11
//emplaza con el ID de la reserva a borrar
