### obtener todos las mesas
GET http://localhost:3000/api/mesas


### obtener una mesa
GET http://localhost:3000/api/mesas/1

### obtener mesas libres
GET http://localhost:3000/api/mesas/libres/1/2023-11-30 10:00:00/afuera

### crear una nueva mesa
POST http://localhost:3000/api/mesas
Content-Type: application/json

{
  "capacidad": 6,
  "ubicacion": "afuera"
}

### modificar una mesa (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/mesas/1
Content-Type: application/json

{
  "capacidad": 4
}

### borrar una mesa
DELETE http://localhost:3000/api/mesas/15