### obtener todos las mesas
GET http://localhost:3000/api/mesas


### obtener una mesa
GET http://localhost:3000/api/mesas/1

### obtener mesas libres
GET http://localhost:3000/api/mesas/libres/1/2023-10-29T19:00:00/afuera

### crear una nueva mesa
POST http://localhost:3000/api/mesas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMTgwNDQ2OSwiZXhwIjoxNzAxODA4MDY5fQ.n9kkcwfqYqk6PvH1HE6m4iWHatA03bZHSlHfDhXyTDw
Content-Type: application/json

{
  "capacidad": "6",
  "ubicacion": "afuera"
}

### modificar una mesa (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/mesas/1
Content-Type: application/json

{
  "capacidad": 4
}

### borrar una mesa
DELETE http://localhost:3000/api/mesas/15