### obtener todos las mesas
GET http://localhost:3000/api/mesas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3MjM5OSwiZXhwIjoxNzAyODc1OTk5fQ.8Z-ML8f4KDA0CufqKM7ytAa0N753Gh0TjvvsuzwB0JA

### obtener una mesa
GET http://localhost:3000/api/mesas/1

### obtener mesas libres
GET http://localhost:3000/api/mesas/libres/1/2023-10-29T19:00:00/afuera

### crear una nueva mesa
POST http://localhost:3000/api/mesas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3MjM5OSwiZXhwIjoxNzAyODc1OTk5fQ.8Z-ML8f4KDA0CufqKM7ytAa0N753Gh0TjvvsuzwB0JA
Content-Type: application/json

{
  "capacidad": "2",
  "ubicacion": "adentro"
}

### modificar una mesa (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/mesas/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbCI6ImFkbWluIiwiaWF0IjoxNzAyODcyNDI2LCJleHAiOjE3MDI4NzYwMjZ9.gJGmor54FF6TZh_767A0e6ACt3lnM0n0cPq8MQ9PT2E
Content-Type: application/json

{
  "capacidad": 4,
  "ubicacion": "adentro"
}

### borrar una mesa
DELETE http://localhost:3000/api/mesas/15