### Obtener todas las reseñas
GET http://localhost:3000/api/resenias

### Obtener una reseña
GET http://localhost:3000/api/resenias/2

### Obtener resela por id de cliente
GET http://localhost:3000/api/resenias/id/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA

### Obtener resela por id de cliente
GET http://localhost:3000/api/resenias/id/2

### Crear una nueva reseña
POST http://localhost:3000/api/resenias/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA
Content-Type: application/json

{
  "comentario": "Buena atencion",
  "puntaje": 3,
  "idCliente": 2
}

### Modificar una reseña (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/resenias/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwicm9sIjoiY2xpZW50ZSIsImlhdCI6MTcwMjg3OTkyNiwiZXhwIjoxNzAyODgzNTI2fQ.RkQ1HEYdP2ODYTtYtBv_tD4kHG5ij6FSBEUKgknCrjA
Content-Type: application/json

{
  "puntaje": 4
}

### Borrar una reseña
DELETE http://localhost:3000/api/resenias/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbCI6ImFkbWluIiwiaWF0IjoxNzAyODc5ODE3LCJleHAiOjE3MDI4ODM0MTd9.Mo2NkDE4zRazPe0ITDkGEn5C0YVRZEs5v5dHTV2KSqs
//Remplaza con el ID de la reseña a borrar
