### Obtener todas las reseñas
GET http://localhost:3000/api/resenias

### Obtener una reseña
GET http://localhost:3000/api/resenias/2

### Obtener resela por id de cliente
GET http://localhost:3000/api/resenias/id/2

### Obtener resela por id de cliente
GET http://localhost:3000/api/resenias/id/2

### Crear una nueva reseña
POST http://localhost:3000/api/resenias/
Content-Type: application/json

{
  "comentario": "Buena atencion",
  "puntaje": 3,
  "cliente": 2
}

### Modificar una reseña (PUT - recurso completo e idempotente)

PUT http://localhost:3000/api/resenias/2
Content-Type: application/json

{
  "puntaje": 4
}

### Borrar una reseña
DELETE http://localhost:3000/api/resenias/5
//Remplaza con el ID de la reseña a borrar
