### obtener todos los clientes
GET http://localhost:3000/api/clientes


### obtener un cliente
GET http://localhost:3000/api/clientes/1

### crear un nuevo cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "dni": "32323234",
  "nombre": "Adam",
  "apellido": "Bareiro",
  "telefono": "3413334387",
  "mail": "ab9@gmail.com",
  "password": "asd"
}

### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/clientes/1
Content-Type: application/json

{
  "mail": "alexam@gmail.com"
}

### borrar un cliente
DELETE http://localhost:3000/api/clientes/12