### obtener todos los clientes
GET http://localhost:3000/api/clientes


### obtener un cliente
GET http://localhost:3000/api/clientes/1

### crear un nuevo cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "dni": "43378663",
  "nombre": "Nahuel",
  "apellido": "Barrios",
  "telefono": "3413334310",
  "mail": "nbp@gmail.com",
  "password": "asd"
}

### modificar un cliente (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/clientes/1
Content-Type: application/json

{
  "mail": "alexam@gmail.com"
}

### borrar un cliente
DELETE http://localhost:3000/api/clientes/5

### login
POST http://localhost:3000/api/clientes/login
Content-Type: application/json

{
  "dni": "43378663",
  "password": "asd"
}

## findbyDni
GET http://localhost:3000/api/clientes/dni/23232324
Content-Type: application/json